learning_log/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('learning_logs.urls')),
    path("users/", include('user.urls'))
]

learning_logs/urls.py
from django.urls import path
from . import views
app_name = "learning_logs"

urlpatterns = [
    path("", views.index, name="home"),
    path("topics/", views.topics, name="topics"),
    path('topic/<int:topic_id>', views.topic, name='topic'),
    path("topics/new_topic", views.new_topic, name="new_topic"),
    path("new_entry/<int:topic_id>", views.new_entry, name='new_entry'),
    path("topic/edit_entry/<int:entry_id>", views.edit_entry, name="edit_entry"),
    path("delete_entry/<int:entry_id>", views.delete_entry, name='delete_entry'),
    path("entry/<int:entry_id>", views.entry, name="entry"),
    path("entry/month_filter/<int:month>", views.month_filter, name='month')
]

user/urls.py
from django.urls import path, include
from . import views
app_name = 'user'

urlpatterns = [
    path("", include('django.contrib.auth.urls')),
    path("register/", views.register, name='register'),
    path("user/<int:user_id>", views.profile, name='profile'),
    path("logout", views.log_out, name="logout")
]

learning_logs/models.py
from django.db import models
from django.contrib.auth.models import User
from django.core.exceptions import ValidationError
from better_profanity import profanity

class Topic(models.Model):
    text = models.TextField(max_length=100, unique=True)
    date_added = models.DateTimeField(auto_now_add=True)
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    verified = models.BooleanField(default=False)
    views = models.PositiveIntegerField(default=0)
    def __str__(self):
        return self.text
    def censorship(self):
        if profanity.censor(self.text) != self.text:
            raise ValidationError("Do not use bad language in your topic !")
        
    def save(self, *args, **kwargs):
        self.censorship()  # call the censorship() method to check for bad language
        super().save(*args, **kwargs)  # call the original save() method to save the model

class Entry(models.Model):
    topic = models.ForeignKey(Topic, on_delete=models.CASCADE)
    text = models.TextField(unique=True)
    date_added = models.DateTimeField(auto_now_add=True)
    verified = models.BooleanField(default=False)
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    #views = models.PositiveIntegerField(default=0)

    class Meta:
        verbose_name_plural = 'entries'
    def __str__(self):
        return f"{self.text[:50]}..."
    
    def clean(self):
        # Split the text field into words
        words = self.text.split()
        # Check if there are at least 250 words
        if len(words) < 250:
            raise ValidationError('The text field must contain at least 250 words.')
    def censorship(self):
        # Check if the text contains profanity
        if profanity.censor(self.text) != self.text:
            raise ValidationError("Do not use bad language in your entry !")
        
    def save(self, *args, **kwargs):
        self.full_clean()  # call the clean() method to validate the model
        self.censorship()  # call the censorship() method to check for bad language
        super().save(*args, **kwargs)  # call the original save() method to save the model

learning_logs/forms.py
from django import forms
from .models import Topic, Entry
class TopicForm(forms.ModelForm):
    class Meta:
        model = Topic
        fields = ['text']
        labels = {"text" : ""}
        widgets = {"text": forms.TextInput(attrs={"placeholder": "Enter the title"})}
class EntryForm(forms.ModelForm):
    class Meta:
        model = Entry
        fields = ['text']
        labels = {"text" : ""}
        widgets = {'text' : forms.Textarea(attrs={'cols' : 80, "placeholder" : "Enter more than 250 words"})}

learning_logs/views.py
from django.shortcuts import render, redirect
from .models import Topic, Entry
from .forms import TopicForm, EntryForm
from django.contrib.auth.decorators import login_required
from django.http import Http404
from better_profanity import profanity
from django.core.exceptions import PermissionDenied
from django.contrib import messages
from django.core.exceptions import ValidationError
import calendar

def index(request):
    entries = Entry.objects.filter(verified=True)
    topic = Topic.objects.filter(verified=True)
    topics = topic.order_by('-views')
    context = {"entries" : entries, "topics" : topics}
    return render(request, 'learning_logs/index.html', context)

def topics(request):
    verified = Topic.objects.filter(verified=True)
    topics = verified.order_by("-date_added")
    context = {"topics" : topics}
    return render(request,"learning_logs/topics.html", context)

def topic(request, topic_id):
    topic = Topic.objects.get(id=topic_id)
    topic.views += 1
    topic.save()
    entry = topic.entry_set.filter(verified=True)
    entries = entry.order_by('-date_added').select_related('author')
    context = {'topic': topic, 'entries': entries}
    return render(request, 'learning_logs/topic.html', context)

def entry(request, entry_id):
    entry = Entry.objects.get(id=entry_id)
    #entry.views += 1
    topic = entry.topic
    user = entry.author
    
    context = {"entry" : entry, "topic" : topic, "user" : user}
    return render(request, "learning_logs/entry.html", context)

def month_filter(request, month):
    dates = Entry.objects.filter(date_added__month=month)
    month_name = calendar.month_name[int(month)]
    context = {'dates' : dates,"month" : month_name}
    return render(request, "learning_logs/date_filter.html", context)

@login_required
def new_topic(request):
    form = TopicForm()
    if request.method == "POST":
        form = TopicForm(request.POST)
        if form.is_valid():
            new_topic = form.save(commit=False)
            new_topic.author = request.user
            try:
                new_topic.save()  # try to save the entry
            except ValidationError as e:
                # handle validation error by adding error message to form
                form.add_error('text', e.message)
            else:
                return redirect("learning_logs:topics")
    context = {"form" : form}
    return render(request, "learning_logs/new_topic.html", context)

@login_required
def new_entry(request, topic_id):
    topic = Topic.objects.get(id=topic_id)
    form = EntryForm()
    if request.method == "POST":
        form = EntryForm(request.POST)
        if form.is_valid():
            new_entry = form.save(commit=False)
            new_entry.topic = topic
            new_entry.author = request.user
            new_entry.verified = True
            try:
                new_entry.save()  # try to save the entry
            except ValidationError as e:
                # handle validation error by adding error message to form
                form.add_error('text', e.message)
            else:
                return redirect("learning_logs:topic", topic_id=topic_id)
    context = {"form" : form, "topic" : topic}
    return render(request, "learning_logs/new_entry.html", context)
@login_required
def edit_entry(request, entry_id):
    entry = Entry.objects.get(id=entry_id)
    topic = entry.topic
    if entry.author != request.user:
       raise Http404
    if request.method != 'POST':
        form = EntryForm(instance=entry)
    else:
        # Отправка данных POST; обработать данные.
        form = EntryForm(data=request.POST)
        if form.is_valid():
            new_entry = form.save(commit=False)
            new_entry.topic = topic
            new_entry.author = request.user
            new_entry.verified = True
            try:
                new_entry.save()  # try to save the entry
            except ValidationError as e:
                # handle validation error by adding error message to form
                form.add_error('text', e.message)
            else:
                entry.delete()
                return redirect("learning_logs:topic", topic_id=topic.id)
    context = {'entry': entry, 'topic': topic, 'form': form}
    return render(request, 'learning_logs/edit_entry.html', context)

@login_required
def delete_entry(request, entry_id):
    entry = Entry.objects.get(id=entry_id)  
    if entry.author != request.user:
        raise PermissionDenied
    else:
        entry.delete()
    return redirect(request.META.get('HTTP_REFERER'))

learning_logs/templates/learning_logs/date_filter.html
{% extends 'base.html' %}

{% block title %}
    <title> {{month}} posts | BLOG</title>
{% endblock title %}

{% block header %}
    <p class="d-inline-block text-center display-4"> Posts created in {{month}} </p>
{% endblock header %}

{% block content %}
    {% for date in dates %}

    <div class="card mb-3">
        <h4 class="card-header d-flex justify-content-around">
           
            {% if request.user == date.author %}
                <a class="d-inline-block display-5 text-decoration-none" href="{% url 'learning_logs:edit_entry' date.id  %}">Edit entry</a>
                <a class="d-inline-block display-5 text-decoration-none" href="#">Delete entry</a>
                <p class="d-inline-block text-right">Entry Creator: <a class="d-inline-block display-5 text-decoration-none" href="{% url 'user:profile' request.user.id %}"> You</a></p>
            {% else %}
            <p class="d-inline-block text-right">Entry Creator:<a class="d-inline-block display-5 text-decoration-none" href="">{{date.author.username}}</a></p>
            {% endif %}
        </h4>
        <div class="card-body">
            <a href="{% url 'learning_logs:entry' date.id %}">{{ date.text|truncatechars:500 }}</a>
        </div>
        
    <footer class="footer">
        <p class="pl-2"> Topic :  <a href="{% url 'learning_logs:topic' date.topic.id %}" class="text-decoration-none d-inline-block" >{{date.topic}}</a></p>
     </footer>
    </div>
    {% empty %}
        <p>There are no entries for this topic yet.</p>
{% endfor %}
{% endblock %}

learning_logs/templates/learning_logs/edit_entry.html
{% extends 'base.html' %}
{% load bootstrap4 %}

{% block content %}
    <a href="{% url 'learning_logs:topic' topic.id %}">{{topic.text}}</a>
    <form class="form" action="{% url 'learning_logs:edit_entry' entry.id %}" method="POST">
        <br>
        {% csrf_token %}
        {% bootstrap_form form %}
        {% buttons %}
        <button name="submit" class="btn btn-primary">Edit</button>
        {% endbuttons %}
    </form>
        <h3>Your post will be showed on the website as soon as administration will verify it.</h3>

{% endblock content %}

learning_logs/templates/learning_logs/entry.html
{% extends 'base.html' %}

{% block title %}
    <title>Entry created by {{entry.author}} | BLOG</title>
{% endblock title %}

{% block header %}
    <div class="border bg-dark text-light p-5 mb-5">
        <h1 class="f6 text-light">Entry created by <a href="{% url 'user:profile' user.id %}">{{entry.author}}</a> with topic <kbd><a href="{% url 'learning_logs:topic' topic.id %}">{{topic.text}}</a></kbd></h1>
</div>
{% endblock header %}

{% block content %}
        <div class="card mb-3">
            <h4 class="card-header d-flex justify-content-around">
               <p class="d-inline-block"> Date posted : {{ entry.date_added|date:'M-d' }} </p>
            </h4>
            <div class="card-body">
                {{ entry.text|linebreaks }}
            </div>
        </div>
{% endblock content %}

learning_logs/templates/learning_logs/index.html
{% extends 'base.html' %}

{% block title %}

    <title>Home Page | BLOG</title>

{% endblock %}

{% block header %}

    <div class="p-5 border border-danger mb-5">
        <h1 class="dispay-3">Track your learning</h1>
        <p class="lead">Make your own Learning Log, and keep a list of the topics you're learning about. Whenever you learn something new about a topic, make an entry summarizing what you've learned.</p>
            {% if user.is_authenticated %}
            
            {% else %}
            <a class="btn btn-lg btn-primary" href="{% url 'user:register' %}" role="button">Register &raquo;</a>
            {% endif %}
    </div>

{% endblock header %}

{% block content %}
<h2>Popular categories: </h2>
    {% for topic in topics %}

        <a class="d-inline-block pr-5 lead h-1 font-weight-bold" href="{% url 'learning_logs:topic' topic.id %}">{{topic.text}}</a>

    {% endfor %}
{% endblock %}

learning_logs/templates/learning_logs/new_entry.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% block title %}
<title>Create new entry on {{topic}} topic | BLOG</title>
{% endblock %}
{% block content %}
    {% if messages %}
    <ul class="messages">
        {% for message in messages %}
        <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
        {% endfor %}
    </ul>
    {% endif %}
    <h2><a id="lnk" href="{% url 'learning_logs:topic' topic.id %}">{{topic.text}}</a></h2>
    <form action="{% url 'learning_logs:new_entry' topic.id %}" method="POST">
        {% csrf_token %}
        {% bootstrap_form form %}
        {% buttons %}
        <button name="submit" class="btn btn-primary">Create Entry</button>
        {% endbuttons %}
    </form>

{% endblock content %}

learning_logs/templates/learning_logs/new_topic.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% block title %}
    <title> Create topic </title>
{% endblock %}
{% block header %}
    <h2>Create a new topic</h2>
{% endblock header %}
{% block content %}

    <form action="{% url 'learning_logs:new_topic' %}" method="POST">
        {% csrf_token %}
        {% bootstrap_form form %}
        {% buttons %}
            <button name="submit" class="btn btn-primary">Add Topic</button>
        {% endbuttons %}
    </form>

{% endblock content %}

learning_logs/templates/learning_logs/topic.html
{% extends 'base.html' %}

{% block title %}
    <title>Posts with topic : {{topic.text}}</title>
{% endblock title %}

{% block header %}
    <div class="border bg-dark text-light p-5 mb-5">
    <h2 class="display-4"> Posts with topic : <code>{{topic}}</code> </h2>
    {% if request.user.is_authenticated %}
    <a class="text-decoration-none lead" href="{% url 'learning_logs:new_entry' topic.id %}">Create entry to this topic. </a>
    {% else %}
    <p>To create new entry please <a href="{% url 'user:login' %}">Login</a> or <a href="{% url 'user:register' %}">Register</a> account</p>
    {% endif %}
</div>
{% endblock header %}

{% block content %}
    {% for entry in entries %}
        <div class="card mb-3">
            <h4 class="card-header d-flex justify-content-around">
               <p class="d-inline-block"> Date posted : <a href="{% url 'learning_logs:month' entry.date_added.month %}">{{ entry.date_added|date:'M-d' }} </a></p>
                {% if request.user == entry.author %}
                    <a class="d-inline-block display-5 text-decoration-none" href="{% url 'learning_logs:edit_entry' entry.id %}">Edit entry</a>
                    <a class="d-inline-block display-5 text-decoration-none" href="{% url 'learning_logs:delete_entry' entry.id %}">Delete entry</a>
                    <p class="d-inline-block text-right">Entry Creator: <a class="d-inline-block display-5 text-decoration-none" href="{% url 'user:profile' entry.author.id %}"> You</a></p>
                {% else %}
                <p class="d-inline-block text-right">Entry Creator:<a class="d-inline-block display-5 text-decoration-none" href="{% url 'user:profile' entry.author.id %}">{{entry.author.username}}</a></p>
                {% endif %}
            </h4>
            <div class="card-body">
                <a href="{% url 'learning_logs:entry' entry.id %}">{{ entry.text|truncatechars:500 }}</a>
            </div>
        </div>
        {% empty %}
            <p>There are no entries for this topic yet.</p>
    {% endfor %}
{% endblock content %}

learning_logs/templates/learning_logs/topics.html
{% extends 'base.html' %}
{% block title %}

    <title>Topics | BLOG</title>

{% endblock title %}
{% block header %}

    <h1 class="display-3">Topics: </h1>

{% endblock header %}
{% block content %}
{% if request.user.is_authenticated %}
<a class="text-decoration-none text-right d-block lead float-right" href="{% url 'learning_logs:new_topic'%}">Create a new topic. </a>
{% else %}
<p>To create new topic please <a href="{% url 'user:login' %}">Login</a> or <a href="{% url 'user:register' %}">Register</a> account</p>
{% endif %}
    <div class="text-dark" >
    {% for topic in topics %}
        <a class="display-4 p-2 text-decoration-none m-2" href="{% url 'learning_logs:topic' topic.id %}"><kbd>{{topic.text}}</kbd></a>
    {% empty %}
        <p>Sorry there are no topics added yet</p>
    {% endfor %}
    </div>
{% endblock %}